server:
  port: 8080

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    password: root
  jpa:
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 156567385594-cicbuulidf4uh282em4i45bkbc4rt60e.apps.googleusercontent.com
            client-secret: ${client.secret}
            scope:
              - email
              - profile
