server:
  port: 9000

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    password: root
  jpa:
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 883744332177-2rcup1qubimrq7mhdhv9m0jibf4pq5ee.apps.googleusercontent.com
            client-secret: ${client.secret}
            scope:
              - email
              - profile
